Document: cjson
Title: Debian cjson Manual
Author: <insert document author here>
Abstract: This manual describes what cjson is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cjson/cjson.sgml.gz

Format: postscript
Files: /usr/share/doc/cjson/cjson.ps.gz

Format: text
Files: /usr/share/doc/cjson/cjson.text.gz

Format: HTML
Index: /usr/share/doc/cjson/html/index.html
Files: /usr/share/doc/cjson/html/*.html
